default:
  secret_key: my_secret
  wtf_csrf_secret_key: my_secret
  admins:
    - matrizaev@gmail.com

production:
  secret_key: PushkindDotCom72
  wtf_csrf_secret_key: PushkindDotCom72
  sqlalchemy_database_uri: "mysql+mysqldb://root:root@0.0.0.0:3306/pushkind?charset=utf8mb4"
