name: Deploy production

on:
  push:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Pull
        run: ssh cicd@vls.pushkind.com "cd /var/www3/html/ && git pull origin main && supervisorctl restart approve_prod"
