name: Test development

on:
  push:
    branches: [ dev ]
    paths:
      - '**.py'
      - '**/pytest.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
          ssh-keygen -t rsa -b 4096 -m PEM -f private.pem
          openssl rsa -in private.pem -pubout -outform PEM -out public.pem
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest
